"""Declarative base and column mixins (spec §10 conventions).

* Deterministic constraint names (``NAMING_CONVENTION``) so Alembic diffs are stable.
* UUID primary keys generated by Postgres (``gen_random_uuid()``, pgcrypto).
* ``timestamptz`` everywhere; ``created_at`` defaults to ``now()`` and ``updated_at`` is
  maintained by the ``tw_set_updated_at()`` trigger function created in migration
  ``0001_extensions``. Each table's migration attaches the trigger.
"""

import uuid
from datetime import datetime
from typing import Final

from sqlalchemy import DateTime, FetchedValue, MetaData, Uuid, func, text
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

UPDATED_AT_TRIGGER_FUNCTION: Final = "tw_set_updated_at"
"""Trigger function (migration 0001) that sets ``updated_at = now()`` on UPDATE."""


class Base(AsyncAttrs, DeclarativeBase):
    """Declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {datetime: DateTime(timezone=True)}  # noqa: RUF012 - SQLAlchemy API


class UUIDPrimaryKeyMixin:
    """``id uuid PRIMARY KEY DEFAULT gen_random_uuid()``."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class TimestampMixin:
    """``created_at``/``updated_at timestamptz NOT NULL DEFAULT now()``."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        server_onupdate=FetchedValue(),
        nullable=False,
    )
